# Generated by Django 2.2 on 2019-05-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClothesComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_comment', models.CharField(max_length=100)),
                ('clothes_gender', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'clothes_comment',
            },
        ),
        migrations.CreateModel(
            name='ClothesIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_des', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'clothes_icon',
            },
        ),
    ]
