# Generated by Django 2.2 on 2019-05-08 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20190507_0757'),
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heart_time', models.DateTimeField(auto_now_add=True)),
                ('cloth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.Cloth')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
            options={
                'db_table': 'heart_time',
            },
        ),
        migrations.AddField(
            model_name='cloth',
            name='hearts2',
            field=models.ManyToManyField(related_name='hearts2', through='clothes.HeartTime', to='user.User'),
        ),
    ]
