# Generated by Django 2.2 on 2019-05-08 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_auto_20190508_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='hearts',
            field=models.ManyToManyField(related_name='hearts2', to='user.User'),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='hearts2',
            field=models.ManyToManyField(related_name='hearts', through='clothes.HeartTime', to='user.User'),
        ),
    ]
