# Generated by Django 2.2 on 2019-05-09 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0002_clothescomment_clothesicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='img_ref',
            field=models.CharField(max_length=2500),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='page_ref',
            field=models.CharField(max_length=2500),
        ),
    ]
