# Generated by Django 2.2 on 2019-05-09 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0004_remove_cloth_hearts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloth',
            old_name='hearts2',
            new_name='hearts',
        ),
    ]
