# Generated by Django 2.2 on 2019-05-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0005_auto_20190509_0313'),
        ('clothes', '0003_auto_20190509_1003'),
    ]

    operations = [
    ]
