# Generated by Django 2.2 on 2019-05-10 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_merge_20190510_0230'),
        ('clothes', '0006_merge_20190509_1520'),
    ]

    operations = [
    ]
