# Generated by Django 2.2 on 2019-05-13 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0007_merge_20190510_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloth',
            name='item_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='temp_max',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cloth',
            name='temp_min',
            field=models.IntegerField(),
        ),
    ]
