# Generated by Django 2.2 on 2019-05-07 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clothes_kind', models.CharField(max_length=100)),
                ('clothes_gender', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'clothes',
            },
        ),
        migrations.CreateModel(
            name='TempCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.IntegerField(default=0)),
                ('temp_max', models.IntegerField(default=0)),
                ('clothes', models.ManyToManyField(to='weather.Clothes')),
            ],
            options={
                'db_table': 'temp_criteria',
            },
        ),
    ]
