# Generated by Django 2.2 on 2019-05-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clothes', '0002_clothescomment_clothesicon'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureCriteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_id', models.IntegerField()),
                ('temp_min', models.IntegerField()),
                ('temp_max', models.IntegerField()),
                ('clothes_comments', models.ManyToManyField(to='clothes.ClothesComment')),
            ],
            options={
                'db_table': 'temperature',
                'ordering': ('temp_id',),
            },
        ),
    ]
