# Generated by Django 2.2 on 2019-05-10 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0006_merge_20190510_0230'),
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturecriteria',
            name='clothes',
            field=models.ManyToManyField(to='clothes.ClothesIcon'),
        ),
    ]
