# Generated by Django 2.2 on 2019-05-07 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempcriteria',
            name='clothes',
        ),
        migrations.DeleteModel(
            name='Clothes',
        ),
        migrations.DeleteModel(
            name='TempCriteria',
        ),
    ]
