# Generated by Django 2.2 on 2019-05-15 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0009_clothesicon_naver_ref'),
        ('weather', '0002_temperaturecriteria_clothes'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempIcon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.ClothesIcon')),
                ('temp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weather.TemperatureCriteria')),
            ],
            options={
                'db_table': 'temp_icon',
            },
        ),
        migrations.AddField(
            model_name='temperaturecriteria',
            name='clothes_icon',
            field=models.ManyToManyField(related_name='temp_icon_name', through='weather.TempIcon', to='clothes.ClothesIcon'),
        ),
    ]
