# Generated by Django 2.2 on 2019-04-30 08:01

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=20)),
                ('user_password', models.CharField(max_length=20)),
                ('user_gender', models.CharField(choices=[(user.models.Gender('M'), 'M'), (user.models.Gender('F'), 'F')], max_length=3)),
            ],
        ),
    ]
