# Generated by Django 2.2 on 2019-05-01 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190430_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_gender',
        ),
    ]
