# Generated by Django 2.2 on 2019-05-01 12:38

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_user_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_gender',
            field=models.CharField(choices=[(user.models.Gender('M'), 'M'), (user.models.Gender('F'), 'F')], default=2, max_length=3),
            preserve_default=False,
        ),
    ]
