# Generated by Django 2.2 on 2019-05-07 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190507_0936'),
        ('user', '0005_auto_20190507_0757'),
    ]

    operations = [
    ]
